/** @type {import('tailwindcss').Config} */

const defaultTheme = require('tailwindcss/defaultTheme');

export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        primary: {
          0: 'var(--ls-ref-palette-primary0)',
          10: 'var(--ls-ref-palette-primary10)',
          20: 'var(--ls-ref-palette-primary20)',
          25: 'var(--ls-ref-palette-primary25)',
          30: 'var(--ls-ref-palette-primary30)',
          35: 'var(--ls-ref-palette-primary35)',
          40: 'var(--ls-ref-palette-primary40)',
          50: 'var(--ls-ref-palette-primary50)',
          60: 'var(--ls-ref-palette-primary60)',
          70: 'var(--ls-ref-palette-primary70)',
          80: 'var(--ls-ref-palette-primary80)',
          90: 'var(--ls-ref-palette-primary90)',
          95: 'var(--ls-ref-palette-primary95)',
          98: 'var(--ls-ref-palette-primary98)',
          99: 'var(--ls-ref-palette-primary99)',
          100: 'var(--ls-ref-palette-primary100)',
          DEFAULT: 'var(--ls-sys-color-primary)',
          container: 'var(--ls-sys-color-primary-container)',
          low: 'var(--ls-sys-color-primary-low)',
          lowest: 'var(--ls-sys-color-primary-lowest)',
          high: 'var(--ls-sys-color-primary-high)',
          highest: 'var(--ls-sys-color-primary-highest)',
        },
        secondary: {
          0: 'var(--ls-ref-palette-secondary0)',
          10: 'var(--ls-ref-palette-secondary10)',
          20: 'var(--ls-ref-palette-secondary20)',
          25: 'var(--ls-ref-palette-secondary25)',
          30: 'var(--ls-ref-palette-secondary30)',
          35: 'var(--ls-ref-palette-secondary35)',
          40: 'var(--ls-ref-palette-secondary40)',
          50: 'var(--ls-ref-palette-secondary50)',
          60: 'var(--ls-ref-palette-secondary60)',
          70: 'var(--ls-ref-palette-secondary70)',
          80: 'var(--ls-ref-palette-secondary80)',
          90: 'var(--ls-ref-palette-secondary90)',
          95: 'var(--ls-ref-palette-secondary95)',
          98: 'var(--ls-ref-palette-secondary98)',
          99: 'var(--ls-ref-palette-secondary99)',
          100: 'var(--ls-ref-palette-secondary100)',
          DEFAULT: 'var(--ls-sys-color-secondary)',
          container: 'var(--ls-sys-color-secondary-container)',
          low: 'var(--ls-sys-color-secondary-low)',
          lowest: 'var(--ls-sys-color-secondary-lowest)',
          high: 'var(--ls-sys-color-secondary-high)',
          highest: 'var(--ls-sys-color-secondary-highest)',
        },
        tertiary: {
          0: 'var(--ls-ref-palette-tertiary0)',
          10: 'var(--ls-ref-palette-tertiary10)',
          20: 'var(--ls-ref-palette-tertiary20)',
          25: 'var(--ls-ref-palette-tertiary25)',
          30: 'var(--ls-ref-palette-tertiary30)',
          35: 'var(--ls-ref-palette-tertiary35)',
          40: 'var(--ls-ref-palette-tertiary40)',
          50: 'var(--ls-ref-palette-tertiary50)',
          60: 'var(--ls-ref-palette-tertiary60)',
          70: 'var(--ls-ref-palette-tertiary70)',
          80: 'var(--ls-ref-palette-tertiary80)',
          90: 'var(--ls-ref-palette-tertiary90)',
          95: 'var(--ls-ref-palette-tertiary95)',
          98: 'var(--ls-ref-palette-tertiary98)',
          99: 'var(--ls-ref-palette-tertiary99)',
          100: 'var(--ls-ref-palette-tertiary100)',
          DEFAULT: 'var(--ls-sys-color-tertiary)',
          container: 'var(--ls-sys-color-tertiary-container)',
          low: 'var(--ls-sys-color-tertiary-low)',
          lowest: 'var(--ls-sys-color-tertiary-lowest)',
          high: 'var(--ls-sys-color-tertiary-high)',
          highest: 'var(--ls-sys-color-tertiary-highest)',
        },
        neutral: {
          0: 'var(--ls-ref-palette-neutral0)',
          10: 'var(--ls-ref-palette-neutral10)',
          20: 'var(--ls-ref-palette-neutral20)',
          25: 'var(--ls-ref-palette-neutral25)',
          30: 'var(--ls-ref-palette-neutral30)',
          35: 'var(--ls-ref-palette-neutral35)',
          40: 'var(--ls-ref-palette-neutral40)',
          50: 'var(--ls-ref-palette-neutral50)',
          60: 'var(--ls-ref-palette-neutral60)',
          70: 'var(--ls-ref-palette-neutral70)',
          80: 'var(--ls-ref-palette-neutral80)',
          90: 'var(--ls-ref-palette-neutral90)',
          95: 'var(--ls-ref-palette-neutral95)',
          98: 'var(--ls-ref-palette-neutral98)',
          99: 'var(--ls-ref-palette-neutral99)',
          100: 'var(--ls-ref-palette-neutral100)',
          variant: {
            0: 'var(--ls-ref-palette-neutral-variant0)',
            10: 'var(--ls-ref-palette-neutral-variant10)',
            20: 'var(--ls-ref-palette-neutral-variant20)',
            25: 'var(--ls-ref-palette-neutral-variant25)',
            30: 'var(--ls-ref-palette-neutral-variant30)',
            35: 'var(--ls-ref-palette-neutral-variant35)',
            40: 'var(--ls-ref-palette-neutral-variant40)',
            50: 'var(--ls-ref-palette-neutral-variant50)',
            60: 'var(--ls-ref-palette-neutral-variant60)',
            70: 'var(--ls-ref-palette-neutral-variant70)',
            80: 'var(--ls-ref-palette-neutral-variant80)',
            90: 'var(--ls-ref-palette-neutral-variant90)',
            95: 'var(--ls-ref-palette-neutral-variant95)',
            98: 'var(--ls-ref-palette-neutral-variant98)',
            99: 'var(--ls-ref-palette-neutral-variant99)',
            100: 'var(--ls-ref-palette-neutral-variant100)',
          },
        },
        error: {
          0: 'var(--ls-ref-palette-error0)',
          10: 'var(--ls-ref-palette-error10)',
          20: 'var(--ls-ref-palette-error20)',
          25: 'var(--ls-ref-palette-error25)',
          30: 'var(--ls-ref-palette-error30)',
          35: 'var(--ls-ref-palette-error35)',
          40: 'var(--ls-ref-palette-error40)',
          50: 'var(--ls-ref-palette-error50)',
          60: 'var(--ls-ref-palette-error60)',
          70: 'var(--ls-ref-palette-error70)',
          80: 'var(--ls-ref-palette-error80)',
          90: 'var(--ls-ref-palette-error90)',
          95: 'var(--ls-ref-palette-error95)',
          98: 'var(--ls-ref-palette-error98)',
          99: 'var(--ls-ref-palette-error99)',
          100: 'var(--ls-ref-palette-error100)',
          DEFAULT: 'var(--ls-sys-color-error)',
          container: 'var(--ls-sys-color-error-container)',
        },
        background: 'var(--ls-sys-color-background)',
        surface: {
          DEFAULT: 'var(--ls-sys-color-surface)',
          tint: 'var(--ls-sys-color-surface-tint)',
          container: {
            DEFAULT: 'var(--ls-sys-color-surface-container)',
            low: 'var(--ls-sys-color-surface-container-low)',
            lowest: 'var(--ls-sys-color-surface-container-lowest)',
            high: 'var(--ls-sys-color-surface-container-high)',
            highest: 'var(--ls-sys-color-surface-container-highest)',
          }
        },
        outline: {
          DEFAULT: 'var(--ls-sys-color-outline)',
          variant: 'var(--ls-sys-color-outline-variant)',
        },
        inverse: {
          on: {
            surface: 'var(--ls-sys-color-inverse-on-surface)',
          },
          surface: 'var(--ls-sys-color-inverse-surface)',
          primary: 'var(--ls-sys-color-inverse-primary)',
        },
        shadow: 'var(--ls-sys-color-shadow)',
        scrim: 'var(--ls-sys-color-scrim)',
        on: {
          primary: {
            DEFAULT: 'var(--ls-sys-color-on-primary)',
            container: 'var(--ls-sys-color-on-primary-container)',
          },
          secondary: {
            DEFAULT: 'var(--ls-sys-color-on-secondary)',
            container: 'var(--ls-sys-color-on-secondary-container)',
          },
          tertiary: {
            DEFAULT: 'var(--ls-sys-color-on-tertiary)',
            container: 'var(--ls-sys-color-on-tertiary-container)',
          },
          error: {
            DEFAULT: 'var(--ls-sys-color-on-error)',
            container: 'var(--ls-sys-color-on-error-container)',
          },
          background: 'var(--ls-sys-color-on-background)',
          surface: {
            DEFAULT: 'var(--ls-sys-color-on-surface)',
            variant: 'var(--ls-sys-color-on-surface-variant)',
          },
        },
      },
      fontFamily: {
        sans: ['var(--ls-sys-font-family-sans)', ...defaultTheme.fontFamily.sans],
        serif: ['var(--ls-sys-font-family-serif)', ...defaultTheme.fontFamily.serif],
      },
      keyframes: {
        'fade-up': {
          from: { 
            transform: 'translateY(50px)',
            opacity: 0,
          },
          to: { 
            transform: 'translateY(0)',
            opacity: 1,
          },
        }
      },
      animation: {
        'fade-up': 'fade-up 700ms ease',
      }
    },
  },
  plugins: [],
}

